"""create currency, meta tables

Revision ID: 2fc8f7c36cf6
Revises: 
Create Date: 2024-02-23 13:53:51.140304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fc8f7c36cf6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("base", sa.String(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currency_base"), "currency", ["base"], unique=False)
    op.create_table(
        "meta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meta_code"), "meta", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meta_code"), table_name="meta")
    op.drop_table("meta")
    op.drop_index(op.f("ix_currency_base"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
